apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apr7-codgen-defaultmodelserver 
  description: Secure Supply Chain Example for Code Generation Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=apr7-codgen-defaultmodelserver  
    janus-idp.io/tekton: apr7-codgen-defaultmodelserver 
    backstage.io/kubernetes-id: apr7-codgen-defaultmodelserver 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jdubrick-ai/apr7-codgen-defaultmodelserver
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 